name: Deploy to Firebase Hosting on Push to Staging
on:
  push:
    branches:
      - main
      - staging
jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.14.2'
      - run: npm ci && npm run build

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P ${{ env.FIREBASE_PROJECT }} --only hosting
        env:
          FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
          VITE_FIREBASE_API_KEY: ${{ env.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ env.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ env.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ env.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ env.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ env.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ env.VITE_FIREBASE_MEASUREMENT_ID }}

    env:
      FIREBASE_TOKEN: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_TOKEN_PRODUCTION || secrets.FIREBASE_TOKEN_STAGING }}
      FIREBASE_PROJECT: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      VITE_FIREBASE_API_KEY: ${{ github.ref == 'refs/heads/main' && secrets.VITE_FIREBASE_API_KEY_PRODUCTION || secrets.VITE_FIREBASE_API_KEY_STAGING }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ github.ref == 'refs/heads/main' && secrets.VITE_FIREBASE_AUTH_DOMAIN_PRODUCTION || secrets.VITE_FIREBASE_AUTH_DOMAIN_STAGING }}
      VITE_FIREBASE_PROJECT_ID: ${{ github.ref == 'refs/heads/main' && secrets.VITE_FIREBASE_PROJECT_ID_PRODUCTION || secrets.VITE_FIREBASE_PROJECT_ID_STAGING }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ github.ref == 'refs/heads/main' && secrets.VITE_FIREBASE_STORAGE_BUCKET_PRODUCTION || secrets.VITE_FIREBASE_STORAGE_BUCKET_STAGING }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ github.ref == 'refs/heads/main' && secrets.VITE_FIREBASE_MESSAGING_SENDER_ID_PRODUCTION || secrets.VITE_FIREBASE_MESSAGING_SENDER_ID_STAGING }}
      VITE_FIREBASE_APP_ID: ${{ github.ref == 'refs/heads/main' && secrets.VITE_FIREBASE_APP_ID_PRODUCTION || secrets.VITE_FIREBASE_APP_ID_STAGING }}
      VITE_FIREBASE_MEASUREMENT_ID: ${{ github.ref == 'refs/heads/main' && secrets.VITE_FIREBASE_MEASUREMENT_ID_PRODUCTION || secrets.VITE_FIREBASE_MEASUREMENT_ID_STAGING }}
      
