name: Deploy to Firebase Hosting on Push to Staging
on:
  push:
    branches:
      - main
      - staging
jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.14.2'
      - run: npm ci && npm run build

      - name: Staging GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P staging --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
          VITE_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY_STAGING }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN_STAGING }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID_STAGING }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET_STAGING }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID_STAGING }}
          VITE_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID_STAGING }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID_STAGING }}

      - name: Production GitHub Action for Firebase
        if: github.ref == 'refs/heads/main'
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P production --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PRODUCTION }}
          VITE_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY_PRODUCTION }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN_PRODUCTION }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID_PRODUCTION }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET_PRODUCTION }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID_PRODUCTION }}
          VITE_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID_PRODUCTION }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID_PRODUCTION }}


