name: Deploy to Firebase Hosting on Push to Staging
on:
  push:
    branches:
      - staging
jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.14.2'
      - run: npm ci && npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P staging --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
